name: Antibytes CI - Label Pull Request Labels

on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
    branches:
      - main
      - feature/**
    paths:
      - '.github/labeler.yml'
      - '.github/labels.yml'
  workflow_dispatch:

jobs:
  add-pr-labels:
    uses: ./.github/workflows/shared-labeler.yml
    with:
      labels-path: .github/labeler.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
