name: Run Checks

on:
  workflow_call:
    inputs:
      cleanup:
        required: false
        type: boolean
        default: true
      projects:
        required: false
        type: string
        default: "[':']"
      build-cache-dir:
        required: false
        type: string
        default: '**/.gradle/build-cache/**'
      restore-only:
        required: false
        type: boolean
        default: true


concurrency:
  group: validation-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      matrix:
        project: fromJson(inputs.projects)

    runs-on: ubuntu-latest

    env:
      GITHUB: ${{ github.workspace }}

    name: Check ${{ matrix.project }}
    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          # gradle-home-cache-includes: ${{ inputs.build-cache-dir }}
          cache-read-only: true

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Restore Konan
        uses: actions/cache/restore@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ github.sha }}
            ${{ runner.os }}-konan-

      - name: Restore BuildCache
        uses: actions/cache/restore@v4
        if: inputs.restore-only == true
        with:
          path: ${{ inputs.build-cache-dir }}
          key: ${{ runner.os }}-build-
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}
            ${{ runner.os }}-build-

      - name: Cache BuildCache
        uses: actions/cache@v4
        if: inputs.restore-only == false
        with:
          path: ${{ inputs.build-cache-dir }}
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}
            ${{ runner.os }}-build-

      - name: Cleanup
        if: inputs.cleanup == true
        run: ./gradlew --no-daemon clean

      - name: Test
        if: endsWith(matrix.project, ':') == false
        continue-on-error: false
        run: ./gradlew --no-daemon ${{ matrix.project }}:test

      - name: Aggregated Test
        if: endsWith(matrix.project, ':') == true
        continue-on-error: false
        run: ./gradlew --no-daemon test

      - name: Publish Test Report
        if: failure()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
