name: Run Checks (Linux)

on:
  workflow_call:
    inputs:
      coverage:
        required: false
        type: boolean
        default: false
      coverage-verification:
        required: false
        type: boolean
        default: false
      cache-reports:
        required: false
        type: boolean
        default: false
      cleanup:
        required: false
        type: boolean
        default: true
      projects:
        required: false
        type: string
        default: "[':app-android']"
      api-level:
        required: false
        type: string
        default: "['29']"
      target:
        required: false
        type: string
        default: "['default']"
      arch:
        required: false
        type: string
        default: "['x86']"
      device:
        required: false
        type: string
        default: "['Nexus 6']"
      emulator-options:
        required: false
        type: string
        default: '-no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim'
      disable-animations:
        required: false
        type: boolean
        default: true
      build-cache-dir:
        required: false
        type: string
        default: '**/.gradle/build-cache/**'

concurrency:
  group: validation-android-${{ github.workflow }}@${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      GITHUB: ${{ github.workspace }}

    strategy:
      matrix:
        api-level: ${{ fromJson(inputs.api-level) }}
        target: ${{ fromJson(inputs.target) }}
        arch: ${{ fromJson(inputs.arch) }}
        device: ${{ fromJson(inputs.device) }}


    name: Check ${{ matrix.api-level }} ${{ matrix.target }} ${{ matrix.arch }} ${{ matrix.device }}
      steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
        with:
          # gradle-home-cache-includes: ${{ inputs.build-cache-dir }}
          cache-read-only: true

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ github.sha }}
            ${{ runner.os }}-konan-

      - name: Restore BuildCache
        uses: actions/cache/restore@v3
        with:
          path: ${{ inputs.build-cache-dir }}
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}
            ${{ runner.os }}-build-

      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: Ensure active AVD
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          force-avd-creation: false
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: ${{ matrix.device }}
          disable-animations: ${{ inputs.disable-animations }}
          emulator-options: ${{ inputs.emulator-options }}
          script: echo "Enable Cache."

      - name: Cleanup
        if: inputs.cleanup == true
        run: ./gradlew --no-daemon clean

      - name: Run Instrumented Tests
        if: endsWith(fromJson(inputs.projects)[0], ':') == false
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: ${{ matrix.device }}
          disable-animations: ${{ inputs.disable-animations }}
          emulator-options: ${{ inputs.emulator-options }}
          script: ./gradlew --no-daemon ${{ join(fromJson(inputs.projects), ':connectedCheck ') }}:connectedCheck

      - name: Run Aggregated Instrumented Tests
        if: endsWith(fromJson(inputs.projects)[0], ':') == true
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          profile: ${{ matrix.device }}
          disable-animations: ${{ inputs.disable-animations }}
          emulator-options: ${{ inputs.emulator-options }}
          script: ./gradlew --no-daemon connectedCheck

      - name: Coverage Android
        if: inputs.coverage == true
        run: ./gradlew --no-daemon --stacktrace androidCoverage

      - name: Verification Android
        if: inputs.coverageVerification == true
        run: ./gradlew --no-daemon --stacktrace androidCoverageVerification

      - name: Publish Test Report
        if: failure()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'

      - name: Cache Reports
        if: inputs.cache-reports == true
        uses: actions/cache/save@v3
        with:
          path: |
            **/reports/detekt/**/*.xml
            **/reports/jacoco/**/*.xml
            **/test-results/**/*
          key: reports-android-${{ github.sha }}
