name: Antibytes CI - Build on MacOs

on:
  workflow_call:
    inputs:
      cache-write-only:
        required: false
        type: boolean
        default: false
      build-cache-dir:
        required: false
        type: string
        default: '**/.gradle/build-cache/**'

jobs:
  build-mac:
    runs-on: macos-latest

    env:
      GITHUB: ${{ github.workspace }}

    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle
        if: inputs.cache-write-only == false
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          # gradle-home-cache-includes: ${{ inputs.build-cache-dir }}

      - name: Setup gradle (write only)
        if: inputs.cache-write-only == true
        uses: gradle/gradle-build-action@v2
        with:
          # gradle-home-cache-includes: ${{ inputs.build-cache-dir }}
          cache-read-only: false
          cache-write-only: true

      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts') }}
            ${{ runner.os }}-konan-

      - name: Cache and Restore BuildCache
        if: inputs.cache-write-only == false
        uses: actions/cache@v3
        with:
          path: ${{ inputs.build-cache-dir }}
          key: ${{ runner.os }}-build-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('*.gradle.kts') }}
            ${{ runner.os }}-build-

      - name: Build # Ensure Build
        run: ./gradlew build -x check --no-daemon --stacktrace

      - name: Cache BuildCache
        if: inputs.cache-write-only == true
        uses: actions/cache/save@v3
        with:
          path: ${{ inputs.build-cache-dir }}
          key: ${{ runner.os }}-build-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('*.gradle.kts') }}
            ${{ runner.os }}-build-
