name: Antibytes CI - Publish Release

on:
  workflow_call:
    inputs:
      build-cache-dir:
        required: false
        type: string
        default: '**/.gradle/build-cache/**'
    
    secrets:
      github-token:
        required: true

jobs:
  release-docs:
    runs-on: ubuntu-latest

    env:
      GITHUB: ${{ github.workspace }}

    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
        with:
          # gradle-home-cache-includes: ${{ inputs.build-cache-dir }}
          cache-read-only: true

      - name: Prepare Python
        run: python3 -m pip install virtualenv --user

      - name: Publish documentation
        env:
          GRGIT_USER: ${{ github.actor }}
          GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew --no-daemon --stacktrace mkdocsPublish -Prelease
