name: Antibytes CI - Build on Linux

on:
  workflow_call:
    inputs:
      cache-write-only:
        required: false
        type: boolean
        default: false

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      GITHUB: true

    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle
        if: inputs.cache-write-only == false
        uses: gradle/gradle-build-action@v2

      - name: Setup gradle (write only)
        if: inputs.cache-write-only == true
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          cache-write-only: true

      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts') }}

      - name: Build # Ensure Build
        run: ./gradlew build -x check --no-daemon --stacktrace
