name:  Antibytes CI - Label Sync

on:
  workflow_call:
    inputs:
      labels-path:
        required: true
        type: string
    secrets:
      github-token:
        required: true

jobs:
  sync:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sync labels
        uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        with:
          manifest: ${{ inputs.labels-path }}
