name: Antibytes CI - Release

on:
  workflow_call:
    inputs:
      uses-mips:
        required: false
        type: boolean
        default: true
    secrets:
      upload-username:
        required: true
      upload-token:
        required: true
      maven-key:
        required: false
      maven-pass:
        required: false
      ossr-username:
        required: true
      ossr-token:
        required: true

jobs:
  snapshot:
    runs-on: macos-latest
    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.upload-username }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.upload-token }}
      MAVEN_PASSPHRASE: ${{ secrets.maven-pass }}
      MAVEN_KEY: ${{ secrets.maven-key }}
      OSSR_USERNAME: ${{ secrets.ossr-username }}
      OSSR_PASSWORD: ${{ secrets.ossr-token }}
    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache Build & Konan
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            **/build/**/*
          key: mac-build

      - name: Build
        run: ./gradlew build -x check --no-daemon --stacktrace

      - name: Publish to Maven Central
        run: ./gradlew publishMavenCentralSnapshot -x build --stacktrace --no-parallel

      - name: Publish to Snapshot Repository
        run: ./gradlew -x build publishSnapshot --no-parallel


  snapshot-mips:
    if: inputs.uses-mips == true
    runs-on: ubuntu-latest
    needs: snapshot
    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.upload-username }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.upload-token }}
      MAVEN_PASSPHRASE: ${{ secrets.maven-pass }}
      MAVEN_KEY: ${{ secrets.maven-key }}
      OSSR_USERNAME: ${{ secrets.ossr-username }}
      OSSR_PASSWORD: ${{ secrets.ossr-token }}
    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Cache Build & Konan
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            **/build/**/*
          key: linux-build

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish Mips to Maven Central Snapshot Repository
        run: ./gradlew publishLinuxMipsMavenCentralSnapshot -x build --no-parallel --stacktrace

      - name: Publish Mips to Snapshot Repository
        run: ./gradlew -x build publishLinuxMipsSnapshot --no-parallel --stacktrace
