name: Antibytes CI - Build on Linux

on:
  workflow_call:
    inputs:
      build-options:
        required: false
        type: string
        default: ''
      cache-write-only:
        required: false
        type: boolean
        default: false
      build-cache-dir:
        required: false
        type: string
        default: '**/.gradle/build-cache/**'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      GITHUB: ${{ github.workspace }}

    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup gradle
        if: inputs.cache-write-only == false
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
          # gradle-home-cache-includes: ${{ inputs.build-cache-dir }}

      - name: Setup gradle (write only)
        if: inputs.cache-write-only == true
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false
          cache-write-only: true
          # gradle-home-cache-includes: ${{ inputs.build-cache-dir }}

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Cache Konan
        uses: actions/cache@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ github.sha }}
            ${{ runner.os }}-konan-

      - name: Cache and Restore BuildCache
        if: inputs.cache-write-only == false
        uses: actions/cache@v4
        with:
          path: ${{ inputs.build-cache-dir }}
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}
            ${{ runner.os }}-build-

      - name: Build # Ensure Build
        run: ./gradlew build ${{ inputs.build-options }} -x check --no-daemon --stacktrace

      - name: Cache BuildCache
        if: inputs.cache-write-only == true
        uses: actions/cache/save@v4
        with:
          path: ${{ inputs.build-cache-dir }}
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}
            ${{ runner.os }}-build-
