name: Antibytes CI - Build on Linux

on:
  workflow_call:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    env:
      GITHUB: true

    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: konan-${{ hashFiles('*.gradle.kts') }}

      - name: Build
        run: ./gradlew build -x check --no-daemon --stacktrace
