name: Run Checks

on:
  workflow_call:
    inputs:
      cleanup:
        required: false
        type: boolean
        default: true
      prefix:
        required: false
        type: string
      api-level:
        required: false
        type: string
        default: 29


concurrency:
  group: validation-${{ github.workflow }}@${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: macos-latest

    name: Check
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Cleanup
        if: inputs.cleanup == true
        run: ./gradlew clean

      - name: Run Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ inputs.api-level }}
          script: ./gradlew :app-android:connectedCheck

      - name: Publish Test Report
        if: failure()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
