name: Run Checks

on:
  workflow_call:
    inputs:
      cleanup:
        required: false
        type: boolean
        default: true
      platforms:
        required: true
        type: string


concurrency:
  group: validation-${{ github.workflow }}@${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      matrix:
        config: [
          { target: android, os: ubuntu-latest, tasks: testDebugUnitTest testReleaseUnitTest, continueOnError: false },
          { target: androidNativeArm, os: ubuntu-latest, tasks: androidNativeArm32Test androidNativeArm64Test, continueOnError: false },
          { target: androidNativeX, os: ubuntu-latest, tasks: androidNativeX64Test androidNativeX86Test, continueOnError: false },
          { target: ios, os: macos-latest, tasks: iosArm64Test iosX64Test iosSimulatorArm64Test, continueOnError: false }
          { target: iosLegacy, os: macos-latest, tasks: iosArm32Test iosArm64Test iosX64Test iosSimulatorArm64Test, continueOnError: false },
          { target: js, os: ubuntu-latest, tasks: jsTest, continueOnError: false },
          { target: jvm, os: ubuntu-latest, tasks: jvmTest, continueOnError: false },
          { target: linuxArm, os: ubuntu-latest, tasks: linuxArm64Test linuxArm32HfpTest, continueOnError: false },
          { target: linuxX, os: ubuntu-latest, tasks: linuxX64Test, continueOnError: false },
          { target: linuxMips, os: ubuntu-latest, tasks: linuxMips32Test linuxMipsel32Test, continueOnError: false },
          { target: macos, os: macos-latest, tasks: macosX64Test macosArm64Test, continueOnError: false },
          { target: tvos, os: macos-latest, tasks: tvosArm64Test tvosX64Test, continueOnError: false },
          { target: watchos, os: macos-latest, tasks: watchosArm32Test watchosArm64Test watchosX64Test watchosSimulatorArm64Test, continueOnError: false },
          { target: watchosLegacy, os: macos-latest, tasks: watchosArm32Test watchosArm64Test watchosX64Test watchosX86Test watchosSimulatorArm64Test, continueOnError: false },
          { target: windows, os: ubuntu-latest, tasks: mingwX86Test mingwX64Test, continueOnError: false },
        ]
    runs-on: ${{ matrix.config.os }}

    name: Check ${{ matrix.config.target }}
    steps:
      - uses: actions/checkout@v3
        if: contains(fromJson(inputs.platforms), matrix.config.target)

      - uses: actions/setup-java@v3
        if: contains(fromJson(inputs.platforms), matrix.config.target)
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup gradle
        if: contains(fromJson(inputs.platforms), matrix.config.target)
        uses: gradle/gradle-build-action@v2

      - name: Cleanup
        if: contains(fromJson(inputs.platforms), matrix.config.target) && ${{ inputs.cleanup == true }}
        run: ./gradlew clean

      - name: Test ${{ matrix.config.target }} targets
        if: contains(fromJson(inputs.platforms), matrix.config.target)
        continue-on-error: ${{ matrix.config.continueOnError }}
        run: ./gradlew ${{ matrix.config.tasks }}

      - name: Publish Test Report
        if: failure() && contains(fromJson(inputs.platforms), matrix.config.target)
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
