name: Antibytes CI - Publish Maven Snapshot

on:
  workflow_call:
    inputs:
      use-linux-only:
        required: false
        type: boolean
        default: false
      uses-mips:
        required: false
        type: boolean
        default: true
      build-cache-dir:
        required: false
        type: string
        default: "['**/build-cache/**', 'caches/build-cache']"
          
    secrets:
      upload-username:
        required: true
      upload-token:
        required: true
      maven-key:
        required: false
      maven-pass:
        required: false
      ossr-username:
        required: true
      ossr-token:
        required: true

jobs:
  snapshot:
    if: inputs.use-linux-only == false
    runs-on: macos-latest

    env:
      GITHUB: ${{ github.workspace }}
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.upload-username }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.upload-token }}
      MAVEN_PASSPHRASE: ${{ secrets.maven-pass }}
      MAVEN_KEY: ${{ secrets.maven-key }}
      OSSR_USERNAME: ${{ secrets.ossr-username }}
      OSSR_PASSWORD: ${{ secrets.ossr-token }}

    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-includes: ${{ inputs.build-cache-dir }}
          cache-read-only: true

      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts') }}
            ${{ runner.os }}-konan-

      - name: Publish to Maven Central
        run: ./gradlew publishMavenCentralSnapshot -x check --stacktrace --no-parallel

      - name: Publish to Snapshot Repository
        run: ./gradlew publishSnapshot -x check --no-parallel


  snapshot-linux-only:
    if: inputs.use-linux-only == true
    runs-on: ubuntu-latest

    env:
      GITHUB: ${{ github.workspace }}
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.upload-username }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.upload-token }}
      MAVEN_PASSPHRASE: ${{ secrets.maven-pass }}
      MAVEN_KEY: ${{ secrets.maven-key }}
      OSSR_USERNAME: ${{ secrets.ossr-username }}
      OSSR_PASSWORD: ${{ secrets.ossr-token }}

    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-includes: ${{ inputs.build-cache-dir }}
          cache-read-only: true

      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts') }}
            ${{ runner.os }}-konan-

      - name: Publish to Maven Central
        run: ./gradlew publishMavenCentralSnapshot -x check --stacktrace --no-parallel

      - name: Publish to Snapshot Repository
        run: ./gradlew publishSnapshot -x check --no-parallel

  snapshot-mips:
    if: inputs.uses-mips == true && inputs.use-linux-only == false
    runs-on: ubuntu-latest
    needs: snapshot

    env:
      GITHUB: ${{ github.workspace }}
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.upload-username }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.upload-token }}
      MAVEN_PASSPHRASE: ${{ secrets.maven-pass }}
      MAVEN_KEY: ${{ secrets.maven-key }}
      OSSR_USERNAME: ${{ secrets.ossr-username }}
      OSSR_PASSWORD: ${{ secrets.ossr-token }}

    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-includes: ${{ inputs.build-cache-dir }}
          cache-read-only: true

      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts') }}
            ${{ runner.os }}-konan-

      - name: Publish Mips to Maven Central Snapshot Repository
        run: ./gradlew publishLinuxMipsMavenCentralSnapshot -x check --no-parallel --stacktrace

      - name: Publish Mips to Snapshot Repository
        run: ./gradlew publishLinuxMipsSnapshot -x check --no-parallel --stacktrace
