name: Antibytes CI - Snapshot

on:
  workflow_call:
    secrets:
      upload-username:
        required: true
      upload-token:
        required: true
      github-token:
        required: false
      maven-key:
        required: false
      maven-pass:
        required: false

jobs:
  snapshot:
    runs-on: macos-latest

    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.upload-username }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.upload-token }}
      MAVEN_KEY: ${{ secrets.maven-key }}
      MAVEN_PASSPHRASE: ${{ secrets.maven-pass }}

    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build -x check --no-daemon --stacktrace

      - name: Publish to Snapshot Repository
        run: ./gradlew publishSnapshot --no-parallel
