name: Antibytes CI - Snapshot

on:
  workflow_call:
    secrets:
      upload-username:
        required: true
      upload-token:
        required: true
      github-token:
        required: false
      maven-key:
        required: false
        default: null
      maven-pass:
        required: false
        default: null

jobs:
  snapshot:
    runs-on: macos-latest

    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.upload-username }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.upload-token }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Set conditional enviroment
        run: |
          echo "MAVEN_PASSPHRASE=${{ secrets.maven-pass }}" >> $GITHUB_ENV
          echo "MAVEN_KEY=${{ secrets.maven-key}}" >> $GITHUB_ENV
        if: maven-pass != null

      - name: Build
        run: ./gradlew build

      - name: Publish to Snapshot Repository
        run: ./gradlew publishSnapshot --no-parallel
