name: Antibytes CI - Snapshot

on:
  workflow_call:
    inputs:
      build-cache-dir:
        required: false
        type: string
        default: '**/.gradle/build-cache/**'
    
    secrets:
      github-token:
        required: true

jobs:
  snapshot-docs:
    runs-on: ubuntu-latest

    env:
      GITHUB: ${{ github.workspace }}

    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Prepare Python
        run: python3 -m pip install virtualenv --user

      - name: Publish documentation
        env:
          GRGIT_USER: ${{ github.actor }}
          GRGIT_PASS: ${{ secrets.github-token }}
        run: ./gradlew --no-configuration-cache --no-daemon --stacktrace mkdocsPublish
