name: Antibytes CI - Pull-Request Form Check

on:
  workflow_call:
    secrets:
      github-token:
        required: true

jobs:
  pull-request-formcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Danger
        uses: docker://ghcr.io/danger/danger-kotlin:1.2.0
        with:
          args: --failOnErrors --no-publish-check
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
