name: Antibytes CI - Labeler

on:
  workflow_call:
    inputs:
      labels-path:
        required: true
        type: string
      github-token:
        required: true
        type: string

jobs:
  configure-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
        with:
          manifest:  ${{ inputs.labels-path }}
