name: Run Checks

on:
  workflow_call:

concurrency:
  group: coverage-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest

    name: Code Coverage
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Coverage
        run: ./gradlew --no-daemon --stacktrace multiplatformCoverageVerification
