name: Antibytes CI - Release

on:
  workflow_call:
    inputs:
      uses-mips:
        required: false
        type: boolean
        default: true
    secrets:
      upload-username:
        required: true
      upload-token:
        required: true
      maven-key:
        required: false
      maven-pass:
        required: false
      ossr-username:
        required: true
      ossr-token:
        required: true

jobs:
  release:
    runs-on: macos-latest
    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.upload-username }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.upload-token }}
      MAVEN_PASSPHRASE: ${{ secrets.maven-pass }}
      MAVEN_KEY: ${{ secrets.maven-key }}
      OSSR_USERNAME: ${{ secrets.ossr-username }}
      OSSR_PASSWORD: ${{ secrets.ossr-token }}
    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Restore Build and Konan
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.konan
            **/build/**/*
          key: mac-build

      - name: Publish to Maven Central
        run: ./gradlew publishMavenCentral -x build --stacktrace --no-parallel

      - name: Publish to Maven Central Repository
        run: ./gradlew publishRollingRelease -x build --no-parallel


  release-mips:
    if: inputs.uses-mips == true
    runs-on: ubuntu-latest
    needs: release
    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.upload-username }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.upload-token }}
      MAVEN_PASSPHRASE: ${{ secrets.maven-pass }}
      MAVEN_KEY: ${{ secrets.maven-key }}
      OSSR_USERNAME: ${{ secrets.ossr-username }}
      OSSR_PASSWORD: ${{ secrets.ossr-token }}
    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Restore Build and Konan
        uses: actions/cache/restore@v3
        with:
          path: |
            ~/.konan
            **/build/**/*
          key: linux-build

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish Mips to Maven Central Repository
        run: ./gradlew publishLinuxMipsMavenCentral -x build --no-parallel --stacktrace

      - name: Publish Mips to Rolling Release Repository
        run: ./gradlew publishLinuxMipsRelease -x build --no-parallel --stacktrace
