name: Run Sonarcloud

on:
  workflow_call:
    inputs:
      detekt:
        required: false
        type: boolean
        default: true
      coverage:
        required: false
        type: boolean
        default: true
      build-cache-dir:
        required: false
        type: string
        default: '**/build-cache/**/*'

    secrets:
      github-token:
        required: false
      sonar-token:
        required: false

concurrency:
  group: coverage-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  coverage:
    runs-on: ubuntu-latest

    env:
      GITHUB: ${{ github.workspace }}
      useSonar: ${{ secrets.sonar-token != '' }}

    name: Code Coverage
    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ hashFiles('*.gradle.kts') }}
            ${{ runner.os }}-konan-

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-includes: ${{ inputs.build-cache-dir }}
          cache-read-only: true

      - name: Cache Reports
        uses: actions/cache@v3
        with:
          path: |
            **/reports/detekt/detekt.xml
            **/reports/jacoco/**/*.xml
            **/test-results/**/*
          key: reports-${{ github.head_ref }}

      - name: Sonarcloud
        env:
          GITHUB_TOKEN: ${{ secrets.github-token }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}
        run: ./gradlew --no-daemon --stacktrace sonarqube --info
