name: Antibytes CI - Snapshot

on:
  workflow_call:
    inputs:
      publish-docs:
        required: true
        type: boolean
    secrets:
      upload-username:
        required: true
      upload-token:
        required: true
      github-token:
        required: false

jobs:
  snapshot:
    runs-on: macos-latest

    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.upload-username }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.upload-token }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'
          cache: gradle

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build

      - name: Prepare Python
        if: inputs.publish-docs
        run: python3 -m pip install virtualenv --user

      - name: Publish documentation
        if: inputs.publish-docs
        env:
          GRGIT_USER: ${{ github.actor }}
          GRGIT_PASS: ${{ secrets.github-token }}
        run: ./gradlew --no-daemon --stacktrace mkdocsPublish

      - name: Publish to Snapshot Repository
        run: ./gradlew publishSnapshot --no-parallel
