name: Antibytes CI - Release

on:
  workflow_call:
    secrets:
      upload-username:
        required: true
      upload-token:
        required: true
      maven-key:
        required: true
      maven-pass:
        required: true
      ossr-username:
        required: true
      ossr-token:
          required: true

jobs:
  publish-release:
    runs-on: macos-latest

    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.upload-username }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.upload-token }}
      MAVEN_PASSPHRASE: ${{ secrets.maven-pass }}
      MAVEN_KEY: ${{ secrets.maven-key }}
      OSSR_USERNAME: ${{ secrets.ossr-username }}
      OSSR_PASSWORD: ${{ secrets.ossr-token }}

    steps:
      - name: Display runner context
        run: hostname -s

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build

      - name: Publish to Maven Central
        run: ./gradlew publishMavenCentral --stacktrace --no-parallel

      - name: Publish to Release Repository
        run: ./gradlew publishRelease --stacktrace --no-parallel
