name: Antibytes CI - Publish Snapshot

on:
  workflow_call:
    inputs:
      use-linux-only:
        required: false
        type: boolean
        default: false
      build-cache-dir:
        required: false
        type: string
        default: '**/.gradle/build-cache/**'
        
    secrets:
      upload-username:
        required: true
      upload-token:
        required: true
      maven-key:
        required: false
      maven-pass:
        required: false

jobs:
  snapshot:
    if: inputs.use-linux-only == false
    runs-on: macos-latest

    env:
      GITHUB: ${{ github.workspace }}
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.upload-username }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.upload-token }}
      MAVEN_PASSPHRASE: ${{ secrets.maven-pass }}
      MAVEN_KEY: ${{ secrets.maven-key }}

    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Restore Konan
        uses: actions/cache/restore@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ github.sha }}
            ${{ runner.os }}-konan-

      - name: Publish to Snapshot Repository
        run: ./gradlew publishSnapshot --stacktrace --no-daemon --no-parallel --no-configuration-cache

  snapshot-linux-only:
    if: inputs.use-linux-only == true
    runs-on: ubuntu-latest

    env:
      GITHUB: ${{ github.workspace }}
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.upload-username }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.upload-token }}
      MAVEN_PASSPHRASE: ${{ secrets.maven-pass }}
      MAVEN_KEY: ${{ secrets.maven-key }}

    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Restore Konan
        uses: actions/cache/restore@v4
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ github.sha }}
            ${{ runner.os }}-konan-

      - name: Publish to Snapshot Repository
        run: ./gradlew publishSnapshot --stacktrace --no-daemon --no-parallel --no-configuration-cache
