name: Run Checks

on:
  workflow_call:
    inputs:
      cleanup:
        required: false
        type: boolean
        default: true
      projects:
        required: false
        type: string
        default: "[':']"


concurrency:
  group: validation-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      matrix:
        project: fromJson(inputs.projects)

    runs-on: ubuntu-latest

    name: Check ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Test
        if: endsWith(matrix.project, ':') == false
        continue-on-error: false
        run: ./gradlew ${{ matrix.project }}:test

      - name: Aggregated Test
        if: endsWith(matrix.project, ':') == true
        continue-on-error: false
        run: ./gradlew test

      - name: Publish Test Report
        if: failure()
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
