name: Antibytes CI - Build on MacOs

on:
  workflow_call:

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Display runner context
        run: hostname -s

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Cache Build & Konan
        uses: actions/cache@v3
        with:
          path: |
            ~/.konan
            **/build/**/*
          key: macos-build-${{ github.head_ref }}

      - name: Build
        run: ./gradlew clean build -x check --no-daemon --stacktrace
