name: Run Checks

on:
  workflow_call:
    inputs:
      platforms:
        required: true
        type: string
      cleanup:
        required: false
        type: boolean
        default: false
      build-cache-dir:
        required: false
        type: string
        default: '**/.gradle/build-cache/**'

concurrency:
  group: validation-${{ github.workflow }}@${{ github.event.pull_request.head.label || github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      matrix:
        config: [
          { target: android, os: ubuntu-latest, tasks: testDebugUnitTest testReleaseUnitTest, continueOnError: false },
          { target: ios, os: macos-latest, tasks: iosX64Test iosSimulatorArm64Test, continueOnError: false },
          { target: js, os: ubuntu-latest, tasks: kotlinUpgradeYarnLock jsTest, continueOnError: false },
          { target: jvm, os: ubuntu-latest, tasks: jvmTest, continueOnError: false },
          { target: linux, os: ubuntu-latest, tasks: linuxX64Test, continueOnError: false },
          { target: linux-all, os: ubuntu-latest, tasks: linuxX64Test jsTest jvmTest testDebugUnitTest testReleaseUnitTest, continueOnError: false },
          { target: linux-js, os: ubuntu-latest, tasks: kotlinUpgradeYarnLock linuxX64Test jsTest, continueOnError: false },
          { target: apple, os: macos-latest, tasks: iosX64Test iosSimulatorArm64Test macosX64Test macosArm64Test tvosX64Test tvosSimulatorArm64Test  watchosX64Test watchosSimulatorArm64Test, continueOnError: false },
          { target: macos, os: macos-latest, tasks: macosX64Test macosArm64Test, continueOnError: false },
          { target: mingw, os: windows-latest, tasks: mingwX64Test, continueOnError: false },
          { target: tvos, os: macos-latest, tasks: tvosX64Test tvosSimulatorArm64Test, continueOnError: false },
          { target: watchos, os: macos-latest, tasks: watchosX64Test watchosSimulatorArm64Test, continueOnError: false },
        ]
    runs-on: ${{ matrix.config.os }}

    env:
      GITHUB: ${{ github.workspace }}

    name: Check ${{ matrix.config.target }}
    steps:
      - name: Checkout Repo
        if: contains(fromJson(inputs.platforms), matrix.config.target)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        if: contains(fromJson(inputs.platforms), matrix.config.target)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup gradle
        if: contains(fromJson(inputs.platforms), matrix.config.target)
        uses: gradle/actions/setup-gradle@v3
        with:
          # gradle-home-cache-includes: ${{ inputs.build-cache-dir }}
          cache-read-only: true

      - name: Validate Gradle Wrapper
        if: contains(fromJson(inputs.platforms), matrix.config.target)
        uses: gradle/wrapper-validation-action@v2

      - name: Restore Konan
        if: contains(fromJson(inputs.platforms), matrix.config.target)
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-konan-${{ github.sha }}
            ${{ runner.os }}-konan-

      - name: Restore BuildCache
        if: ${{ contains(fromJson(inputs.platforms), matrix.config.target) }}
        uses: actions/cache/restore@v4
        with:
          path: ${{ inputs.build-cache-dir }}
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}
            ${{ runner.os }}-build-

      - name: Cleanup
        if: inputs.cleanup == true && contains(fromJson(inputs.platforms), matrix.config.target)
        run: ./gradlew --no-daemon clean

      - name: Test ${{ matrix.config.target }} targets
        if: contains(fromJson(inputs.platforms), matrix.config.target)
        continue-on-error: ${{ matrix.config.continueOnError }}
        run: ./gradlew --no-daemon ${{ matrix.config.tasks }}

      - name: Publish Test Report
        if: failure() && contains(fromJson(inputs.platforms), matrix.config.target)
        uses: mikepenz/action-junit-report@v3
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'
