name: Antibytes CI - Rolling Release

on:
  workflow_call:
    secrets:
      upload-username:
        required: true
      upload-token:
        required: true

jobs:
  rolling-release:
    runs-on: macos-latest

    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.upload-username }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.upload-token }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Setup gradle
        uses: gradle/gradle-build-action@v2

      - name: Build
        run: ./gradlew build -x check --no-daemon --stacktrace

      - name: Publish to Rolling Release Repository
        run: ./gradlew publishRollingRelease --no-parallel
